[project]
name = "mcp-server"
version = "0.1.0"
description = "MCP Server providing function calling capabilities"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastmcp>=0.4.0",
    "httpx>=0.28.0",
    "python-dotenv>=1.0.0",
]
