[project]
name = "agent"
version = "0.1.0"
description = "MAF Agent with MCP tool integration"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "azure-ai-projects>=1.0.0b7",
    "azure-identity>=1.21.1",
    "python-dotenv>=1.0.0",
    "mcp>=1.12.0",
]
