[project]
name = "build-and-push"
version = "0.1.0"
description = "Build and push script for MAF Observability Demo"
requires-python = ">=3.8"
dependencies = [
    "python-dotenv>=1.0.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"